### ISSUE TITLE
Not working on Production

### ISSUE THREAD

**Issue by masterjayr** [nelstein/nravepay#27] opened 2022-01-30 01:00 UTC
Package not working when app built with flutter build apk --split-per-abi

It doesn't move forward after card details are entered. 

It works on debug app but not when in Production. Please need help with this ASAP, thanks

**Comment by nelsonweze** [comment] 2022-01-30 12:51
Could you share the version you are using? 
Is your live transaction turned on in the Dashboard? Did you also try using live keys on debug mode and it worked?
Answer these let me have more information.

**Comment by masterjayr** [comment] 2022-01-30 13:08
Thank you for your prompt response.
Basically I'm using the test keys on the build where it doesn't work
I haven't tried the live keys either on debug mode.

Is there some restriction on the package where the package only works with
the live keys when in production or when built with Flutter build apk?

But to provide more information, I haven't tried live keys on debug mode
yet, I'm using the test keys to test the built application. Thanks, I'll be
expecting your reply.

**Comment by nelsonweze** [comment] 2022-01-30 13:10
Okay got it.. Could you confirm that this issue is reproducible on version 1.2.1-dev.4?

**Comment by masterjayr** [comment] 2022-01-30 13:33
I'm currently using version 1.2.0, Let me confirm with 1.2.1-dev.4 and
revert back to you.

**Comment by masterjayr** [comment] 2022-01-30 14:12
Just Confirmed the issue is reproducible on version 1.2.1-dev.4

**Comment by nelsonweze** [comment] 2022-01-30 15:06
My guess is this is probably some error from Flutterwave but we need logs to confirm that.. I added logging option in the version I sent above but you have to enable in the Setup.  Try flutter run --release on a real device to get the logs.

**Comment by masterjayr** [comment] 2022-01-30 16:13
Thanks, I'll check it out.

**Comment by masterjayr** [comment] 2022-01-30 22:56
Hi @nelstein, after running flutter run --release, this is what is logged out

[1179408211, 1162038111, 1413829460, 1714827832, 1697658932, 1650800697, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

when I click on Pay Now. I wonder if this could help you to debug

**Comment by masterjayr** [comment] 2022-01-31 01:55
tripledes package error here too
I think that might be the root issue

**Comment by nelsonweze** [comment] 2022-01-31 06:02
> Hi @nelstein, after running flutter run --release, this is what is logged out
> 
> [1179408211, 1162038111, 1413829460, 1714827832, 1697658932, 1650800697, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> 
> when I click on Pay Now. I wonder if this could help you to debug

Yeah this log is from tripledes but it's not an error. I believe you are using test cards so give me the details please. We use this package in production and it works fine. I will however investigate

**Comment by nelstein** [comment] 2022-02-07 16:32
Hi @masterjayr  since I you didn't provide the test card details you were using,  I checked the example app and discovered without adding permission to access internet in your AndriodManifest.xml file, it can't make  network requests in release mode.

So try these

1. If you didn't earlier, then add `<uses-permission android:name="android.permission.INTERNET" />` to your android/app/src/main/AndroidManifest.xml just before the application tag and build again.

2. if 1 didn't work, clone the example app and test with your details. Send me logs if any

**Comment by nelsonweze** [comment] 2022-02-09 18:10
Sorry, I am closing this as it's duplicate of #19 
Checkout nravepay: ^1.2.2 if you are still experiencing this issue. 

Re-open if anything

**Closed as completed by nelsonweze** 2022-02-09 18:10 UTC
